### ISSUE TITLE
Make backtest more realistic

### ISSUE THREAD

**Issue by Geukers** [AlgoETS/BullETS#29]
Trading the real world comes with certain issues and the backtests should reflect it.

Add these features
- Slippage (Maybe we could return the open price, but the actual price for buying is anywhere between the high and the low)
- Transactions fees (1$/transaction?)

**Comment by TristanFecteau** [comment]
For slippage, would we set a standard slippage percentage? (for example we average the slippage to 25% and apply that on every trade) 
If not, how do we calculate slippage percentage?
![image](https://user-images.githubusercontent.com/80732570/126384558-fab34f70-ab77-4bc2-9df2-7130374b7418.png)

**Comment by TristanFecteau** [comment]
Transaction fees : make default transaction fee to 1$ and allow backtesters to set that value to anything over 0 $
Slippage : make default slippage percent to 25% and allow backtesters to set that value to anything between 0 and 100%

**Comment by TristanFecteau** [comment]
slippage works, but only with strategies with DAILY resolutions since we differentiate stocks only from their symbol and not their resolutions, we need to change that before pushing this
![image](https://user-images.githubusercontent.com/80732570/127019374-e175d876-3f50-4a6b-a378-e7719816c38f.png)
